### ISSUE TITLE
Compile error and editor does not load

### ISSUE THREAD

**Issue by rodrigopavezi** [angular-ui/ui-tinymce#228]
Hello,

After yesterday's release we are getting the following error and editor does not load. Would you have any clue why this is happening? 

Error: [$compile:ctreq] http://errors.angularjs.org/1.3.20/$compile/ctreq?p0=ngModel&p1=uiTinymce
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.20/angular.min.js:6:417
    at M (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.20/angular.min.js:56:127)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.20/angular.min.js:56:193
    at r (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.20/angular.min.js:7:322)
    at M (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.20/angular.min.js:56:170)
    at I (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.20/angular.min.js:59:293)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.20/angular.min.js:51:335)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.20/angular.min.js:51:352)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.20/angular.min.js:51:352)(anonymous function) @ angular.js:11706(anonymous function) @ angular.js:8619n.$digest @ angular.js:14430(anonymous function) @ angular.js:14609e @ angular.js:4940(anonymous function) @ angular.js:5328

Thank you very much.

**Comment by deeg** [comment]
A priority was added to the directive, could that have something to do with it?

Can you please post a plunker re-creating the issue so we can take a look?

**Comment by deeg** [comment]
Please take a look at [CONTRIBUTING.md](https://github.com/angular-ui/ui-tinymce/blob/master/CONTRIBUTING.md).

If you have found a bug, please open a new issue with a plunker re-creating it.
