### ISSUE TITLE
TypeError: Cannot read property '$$phase' of null

### ISSUE THREAD

**Issue by jojobyte** [angular-ui/ui-tinymce#82]
I am getting the following error when loading a view using this plugin.
```
TypeError: Cannot read property '$$phase' of null
    at updateView (http://localhost:3000/public/components/angular-ui-tinymce/src/tinymce.js:16:29)
    at Object.<anonymous> (http://localhost:3000/public/components/angular-ui-tinymce/src/tinymce.js:51:17)
    at Object.fire (http://localhost:3000/public/components/tinymce/tinymce.min.js:8:8185)
    at Object.N.setContent (http://localhost:3000/public/components/tinymce/tinymce.min.js:8:26019)
    at ngModel.$render (http://localhost:3000/public/components/angular-ui-tinymce/src/tinymce.js:74:26)
    at Object.ngModelWatch (http://localhost:3000/public/components/angular/angular.js:17342:14)
    at Scope.$digest (http://localhost:3000/public/components/angular/angular.js:12243:40)
    at Scope.$apply (http://localhost:3000/public/components/angular/angular.js:12516:24)
    at http://localhost:3000/public/components/angular/angular.js:14023:36
    at completeOutstandingRequest (http://localhost:3000/public/components/angular/angular.js:4300:10) 
```

Changing the following lines from https://github.com/angular-ui/ui-tinymce/blob/master/src/tinymce.js#L16-L18

```javascript
if (!scope.$root.$$phase) {
scope.$apply();
}
```

to

```javascript
if (scope.$root && !scope.$root.$$phase) {
scope.$apply();
}
```

seem to fix it.

**Comment by tezaurus** [comment]
Working! Thank you!

**Comment by ghominejad** [comment]
I have a page controller without any parameters (`app.edit`). angular loads the page without any problem for the first time. but in the next time when i want switch to this page again `$state.go('app.edit')`. angular doesn't load the tinymce control and the same error appears!

**Comment by AndreyKornyenko** [comment]
Bug is reproducing for me

**Comment by Uznick** [comment]
Still reproduces in 0.0.5

**Comment by mudassir0909** [comment]
@Uznick did you find a workaround ?

**Comment by Uznick** [comment]
@mudassir0909 nope, still living with it.

**Comment by mudassir0909** [comment]
:cry: guess I'll use a forked repo until then

**Comment by wesleycho** [comment]
I switched this to `$rootScope`, which is what the code should have referenced - this should now be fixed.

**Comment by krunalsha** [comment]
I have the same issue, and @jojobyte's fix works for me.

**Comment by ervinkleitz** [comment]
@jojobyte fix worked for me. Thanks!

**Comment by webrider** [comment]
Manually Triggering the Digest Cycle. Please use like this: 
$scope.$apply(() => {
     your code here that changes ng-model
});
